### ISSUE TITLE
How to use without ROS？

### ISSUE THREAD

**Issue by Zkjoker** [better-flow/better-flow#1]
When I run the command "./bf_motion_compensator -o result.txt events.txt", however,after running, there wasn't any outfile generated. And I have run the command "./bf_motion_compensator -video  events.txt",and generated an "out.avi",but I can't open it and the error is "couldn't demultiplex stream".
The events.txt is from the the datasets provided by ETH,like "0.000000000 128 154 1","0.000056000 102 26 0",etc.
So can you help me to use your method to motion compensation without ros?

**Comment by ncos** [comment]
Sorry for the late answer. Does it work with -i option? I think '-i' is the only 'stable' option; but I can give you pointers to the parts of the code if you need a particular kind of output. 

For the video - Ubuntu has some issues with codecs; I usually generate images (--img) instead and use ffmpeg to generate a video.
