### ISSUE TITLE
Resolution inconsistancy 

### ISSUE THREAD

**Issue by robin-shaun** [better-flow/better-flow#5]
Why `// Camera resolution #define RES_X 180 #define RES_Y 240` in common.h  and `// Input parameters int resolution_x = 240; int resolution_y = 180;` in bf_viewer.cpp are inconsistant.

**Comment by ncos** [comment]
Not sure what the reason for this is; note that ROS binding was developed separately and later compared to the main code (which was supposed to be ran on events in .txt format)
