### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by robin-shaun** [better-flow/better-flow#7]
I use the algorithm without ROS, and segmentation fault happens.

./bf_motion_compensator-i /home/robin/event_based_vision/dataset/davis346.bag.txt
Reading from file... (/home/robin/event_based_vision/dataset/davis346.bag.txt)
Read and processed 0 events

C: (0, 0); 
	 Shift: (0, 0);  total: (0, 0);
	 Rot: 0 total: 0
	 Div: 0 total: 0
	 cnt: 0

segmentation fault (core dumped)

**Comment by ncos** [comment]
Sorry about that :) well - the code was never really designed for/tested on anything beyond davis 240 (even though there is an experimental support for prophesee/samsung).

**Comment by ncos** [comment]
And, well, I see - looks like for a certain time slice you have 0 events (or your txt format is invalid so it could not read any events?)
Basically the problem starts with 'Read and processed 0 events' error message; segfault is just a symptom

**Comment by ncos** [comment]
@robin-shaun, you will need to look inside the code to understand why it did not read your txt file;
I suggest take a look [here](https://github.com/better-flow/better-flow/blob/master/better_flow_core/include/better_flow/event_file.h#L34)
